# Generated by Django 3.1.6 on 2021-05-15 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210511_0031'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0004_auto_20210417_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewed_lessons', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('percentage', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed', to='courses.course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ViewLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_lessons', to='courses.lesson')),
                ('view_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_lessons_list', to='activity.viewcourse')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
