# Generated by Django 3.1.6 on 2021-04-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
