# Generated by Django 3.1.6 on 2021-04-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='file_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
