# Generated by Django 3.1.6 on 2021-03-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210330_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
