# Generated by Django 3.1.6 on 2021-02-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210212_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(null=True, upload_to='category/'),
        ),
    ]
