# Generated by Django 3.1.6 on 2021-05-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210510_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution',
            name='video',
            field=models.FileField(blank=True, max_length=1500, upload_to=''),
        ),
    ]
