# Generated by Django 3.1.6 on 2021-02-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210216_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
