# Generated by Django 3.1.6 on 2021-03-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210330_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
