# Generated by Django 3.1.6 on 2021-02-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210216_0704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='subject',
            new_name='subcategory',
        ),
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.ImageField(null=True, upload_to='courses/<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
