# Generated by Django 3.1.6 on 2021-02-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210216_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
