# Generated by Django 3.1.6 on 2021-05-27 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210527_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
