# Generated by Django 3.1.6 on 2021-02-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_subcategory_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='module',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_path',
        ),
        migrations.AddField(
            model_name='lesson',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='lesson/<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, upload_to='video/'),
        ),
    ]
