# Generated by Django 3.1.6 on 2021-02-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('CH', 'Для детей'), ('BG', 'Для начинающих'), ('AD', 'Для продвинутых')], default='BG', max_length=2),
        ),
    ]
