# Generated by Django 3.1.6 on 2021-02-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
