# Generated by Django 3.1.6 on 2021-02-28 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20210228_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
