# Generated by Django 3.1.6 on 2021-03-25 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('promocode', models.CharField(blank=True, default='', max_length=20)),
                ('bonus', models.PositiveIntegerField(default=0)),
                ('bill_number', models.CharField(blank=True, default='', max_length=50)),
                ('geo', models.TextField(blank=True, null=True)),
                ('site', models.TextField(blank=True, null=True)),
                ('follow_end', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('custom_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('followings', models.ManyToManyField(blank=True, null=True, related_name='followers', to='authentication.Profile')),
                ('saved', models.ManyToManyField(blank=True, null=True, related_name='saved_by', to='courses.Course')),
            ],
        ),
    ]
