# Generated by Django 3.1.6 on 2021-03-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follow_end',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='promocode',
        ),
    ]
