# Generated by Django 3.1.6 on 2021-04-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('authentication', '0002_profile_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='purchases',
            field=models.ManyToManyField(blank=True, related_name='purchased_users', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='followers', to='authentication.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='courses.Course'),
        ),
    ]
