# Generated by Django 3.1.6 on 2021-02-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bill_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='bonus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='followings',
            field=models.ManyToManyField(related_name='_profile_followings_+', to='authentication.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='geo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='promocode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='site',
            field=models.TextField(blank=True, null=True),
        ),
    ]
