# Generated by Django 3.1.6 on 2021-02-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210223_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followings',
            field=models.ManyToManyField(related_name='followers', to='authentication.Profile'),
        ),
    ]
