# Generated by Django 3.1.6 on 2021-02-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210223_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
