# Generated by Django 3.1.6 on 2021-02-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20210219_0640'),
        ('authentication', '0006_auto_20210223_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follow_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='saved',
            field=models.ManyToManyField(related_name='saved_by', to='courses.Course'),
        ),
    ]
