# Generated by Django 3.1.6 on 2021-02-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20210219_0640'),
        ('authentication', '0007_auto_20210223_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followings',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to='authentication.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='saved',
            field=models.ManyToManyField(blank=True, null=True, related_name='saved_by', to='courses.Course'),
        ),
    ]
