from educa.apps.courses.serializers import CategoryDetailSerializer
from django.urls import path
from .views import (AllSubcategoryListView, CategoryListView,
                    CourseDetailView, 
                    CourseListView,   
                    LessonDetailView, 
                    LessonListView, 
                    LevelListView, 
                    SubcategoryListView, 
                    course_save, 
                    is_course_saved,
                    tmp,
                    delete_course_photo,
                    )

urlpatterns = [
    path('categories', CategoryListView.as_view(), name='category_list'),
    path('courses', CourseListView.as_view(), name='all_course_list'),
    path('subcategories/<int:id>', SubcategoryListView.as_view(), name='subcategory_list'),
    path('allsubcategories/<int:id>', AllSubcategoryListView.as_view(), name='subcategory_list'),
    path('courses/<slug:category>', CourseListView.as_view(), name='course_list'),
    path('courses/<slug:category>/<slug:subcategory>', CourseListView.as_view(), name='course_list_sub'),
    path('course/<int:pk>', CourseDetailView.as_view(), name='course_detail'),
    path('course/<int:pk>/delete', CourseDetailView.as_view(), name='course_delete'),
    path('course/<int:pk>/photo', delete_course_photo, name='delete_course_photo'),
    path('course/<int:pk>/put', CourseDetailView.as_view(), name='course_put'),
    path('course/create', CourseDetailView.as_view(), name='course_create'),
    path('course/save', course_save, name='save_course'),
    path('course/issaved', is_course_saved, name='save_course'),
    path('lessons/<int:course_id>', LessonListView.as_view(), name='lesson_list'),
    path('lessons', LessonListView.as_view(), name='lesson_all_list'),
    path('lesson/<int:id>', LessonDetailView.as_view(), name='lesson_detail'),
    path('lesson/create', LessonDetailView.as_view(), name='lesson_create'),
    path('levels', LevelListView.as_view(), name='level_list'),
    path('tmp/create', tmp, name='tmp_create'),
    path('tmp/delete', tmp, name='tmp_delete'),
]
